# backend/seed_data.py
from database import personnel_collection
from sentence_transformers import SentenceTransformer
import json

print("Loading embedding model... (first time may take a minute)")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded.")

personnel_data = [
    {"employee_id": "DRDO-1001", "full_name": "Dr. Rajesh Kumar", "gender": "Male", "designation": "Scientist G", "department": "Aeronautics", "lab_acronym": "ADE", "area_of_expertise": ["Aerodynamics", "Flight Control Systems", "UAV Design"], "projects_associated": ["Project RUSTOM", "Project AURA"], "phone_office": "080-25051001", "email": "rajesh.kumar@ade.drdo.in", "years_of_experience": 22},
    {"employee_id": "DRDO-1002", "full_name": "Dr. Priya Sharma", "gender": "Female", "designation": "Scientist F", "department": "Electronics & Radar", "lab_acronym": "LRDE", "area_of_expertise": ["Radar Signal Processing", "Phased Array Antenna", "Embedded Systems"], "projects_associated": ["Project ARUDHRA", "Project UTTAM"], "phone_office": "080-25051002", "email": "priya.sharma@lrde.drdo.in", "years_of_experience": 18},
    {"employee_id": "DRDO-1003", "full_name": "Dr. Anil Verma", "gender": "Male", "designation": "Scientist H", "department": "Missiles & Strategic Systems", "lab_acronym": "DRDL", "area_of_expertise": ["Missile Propulsion", "Ballistic Systems", "Rocket Engineering"], "projects_associated": ["Project AGNI", "Project PRITHVI"], "phone_office": "040-24586003", "email": "anil.verma@drdl.drdo.in", "years_of_experience": 30},
    {"employee_id": "DRDO-1004", "full_name": "Ms. Sunita Rao", "gender": "Female", "designation": "Scientist D", "department": "Cyber Security", "lab_acronym": "CAIR", "area_of_expertise": ["Network Security", "Cryptography", "Ethical Hacking"], "projects_associated": ["Project NETRA", "CyberShield"], "phone_office": "080-23600004", "email": "sunita.rao@cair.drdo.in", "years_of_experience": 8},
    {"employee_id": "DRDO-1005", "full_name": "Dr. Vikram Singh", "gender": "Male", "designation": "Scientist F", "department": "Naval Systems", "lab_acronym": "NSTL", "area_of_expertise": ["Underwater Acoustics", "Torpedo Systems", "Naval Warfare"], "projects_associated": ["Project VARUNASTRA", "Project SHYENA"], "phone_office": "0891-2543005", "email": "vikram.singh@nstl.drdo.in", "years_of_experience": 16},
    {"employee_id": "DRDO-1006", "full_name": "Dr. Meena Iyer", "gender": "Female", "designation": "Scientist G", "department": "Life Sciences", "lab_acronym": "DIPAS", "area_of_expertise": ["High Altitude Medicine", "Physiology", "Nutrition Science"], "projects_associated": ["Project HIMSHAKTI", "AltitudeCare"], "phone_office": "011-23883006", "email": "meena.iyer@dipas.drdo.in", "years_of_experience": 20},
    {"employee_id": "DRDO-1007", "full_name": "Mr. Arjun Nair", "gender": "Male", "designation": "Scientist C", "department": "Electronics & Radar", "lab_acronym": "LRDE", "area_of_expertise": ["VLSI Design", "FPGA Programming", "Signal Processing"], "projects_associated": ["Project UTTAM"], "phone_office": "080-25051007", "email": "arjun.nair@lrde.drdo.in", "years_of_experience": 5},
    {"employee_id": "DRDO-1008", "full_name": "Dr. Kavitha Menon", "gender": "Female", "designation": "Scientist E", "department": "Armaments", "lab_acronym": "ARDE", "area_of_expertise": ["Explosives Chemistry", "Warhead Design", "Ballistics"], "projects_associated": ["Project PINAKA", "Project BRAHMOS"], "phone_office": "020-27213008", "email": "kavitha.menon@arde.drdo.in", "years_of_experience": 12},
    {"employee_id": "DRDO-1009", "full_name": "Dr. Suresh Patel", "gender": "Male", "designation": "Scientist F", "department": "Materials Science", "lab_acronym": "DMRL", "area_of_expertise": ["Advanced Composites", "Metallurgy", "Ceramic Armour"], "projects_associated": ["ArmorTech", "Project KANCHAN"], "phone_office": "040-24340009", "email": "suresh.patel@dmrl.drdo.in", "years_of_experience": 17},
    {"employee_id": "DRDO-1010", "full_name": "Ms. Anjali Desai", "gender": "Female", "designation": "Scientist D", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Machine Learning", "Computer Vision", "Deep Learning"], "projects_associated": ["Project AI-GUARD", "SmartSurveillance"], "phone_office": "080-23600010", "email": "anjali.desai@cair.drdo.in", "years_of_experience": 7},
    {"employee_id": "DRDO-1011", "full_name": "Dr. Raman Tiwari", "gender": "Male", "designation": "Scientist G", "department": "Missiles & Strategic Systems", "lab_acronym": "DRDL", "area_of_expertise": ["Guidance Systems", "Navigation", "Control Engineering"], "projects_associated": ["Project AGNI-5", "Project NISHANT"], "phone_office": "040-24586011", "email": "raman.tiwari@drdl.drdo.in", "years_of_experience": 25},
    {"employee_id": "DRDO-1012", "full_name": "Dr. Lakshmi Krishnan", "gender": "Female", "designation": "Scientist F", "department": "Electronics & Radar", "lab_acronym": "SAC", "area_of_expertise": ["Remote Sensing", "Satellite Communication", "Image Processing"], "projects_associated": ["Project RISAT", "EO Payload"], "phone_office": "079-26914012", "email": "lakshmi.krishnan@sac.drdo.in", "years_of_experience": 15},
    {"employee_id": "DRDO-1013", "full_name": "Mr. Deepak Joshi", "gender": "Male", "designation": "Scientist C", "department": "Cyber Security", "lab_acronym": "CAIR", "area_of_expertise": ["Malware Analysis", "Intrusion Detection", "Forensics"], "projects_associated": ["CyberShield", "Project NETRA"], "phone_office": "080-23600013", "email": "deepak.joshi@cair.drdo.in", "years_of_experience": 4},
    {"employee_id": "DRDO-1014", "full_name": "Dr. Ananya Bose", "gender": "Female", "designation": "Scientist E", "department": "Aeronautics", "lab_acronym": "NAL", "area_of_expertise": ["Computational Fluid Dynamics", "Wind Tunnel Testing", "Aircraft Structures"], "projects_associated": ["Project SARAS", "Project HANSA"], "phone_office": "080-25051014", "email": "ananya.bose@nal.drdo.in", "years_of_experience": 11},
    {"employee_id": "DRDO-1015", "full_name": "Dr. Pramod Gupta", "gender": "Male", "designation": "Scientist H", "department": "Nuclear Medicine", "lab_acronym": "INMAS", "area_of_expertise": ["Radiation Protection", "Nuclear Medicine", "Dosimetry"], "projects_associated": ["RadShield", "NBC Protection"], "phone_office": "011-23905015", "email": "pramod.gupta@inmas.drdo.in", "years_of_experience": 28},
    {"employee_id": "DRDO-1016", "full_name": "Ms. Rekha Pillai", "gender": "Female", "designation": "Scientist D", "department": "Naval Systems", "lab_acronym": "NPOL", "area_of_expertise": ["Sonar Systems", "Signal Processing", "Oceanography"], "projects_associated": ["Project HUMSA", "NavalSonar-2"], "phone_office": "0484-2575016", "email": "rekha.pillai@npol.drdo.in", "years_of_experience": 9},
    {"employee_id": "DRDO-1017", "full_name": "Dr. Sanjay Mehta", "gender": "Male", "designation": "Scientist F", "department": "Armaments", "lab_acronym": "TBRL", "area_of_expertise": ["Terminal Ballistics", "Vulnerability Assessment", "Ammunition Testing"], "projects_associated": ["Project PINAKA", "AmmunitionTest-3"], "phone_office": "0172-2635017", "email": "sanjay.mehta@tbrl.drdo.in", "years_of_experience": 14},
    {"employee_id": "DRDO-1018", "full_name": "Dr. Usha Nambiar", "gender": "Female", "designation": "Scientist G", "department": "Life Sciences", "lab_acronym": "DFRL", "area_of_expertise": ["Food Technology", "Preservation Science", "Nutritional Research"], "projects_associated": ["SoldierNutrition", "FieldRation-5"], "phone_office": "0821-2362018", "email": "usha.nambiar@dfrl.drdo.in", "years_of_experience": 21},
    {"employee_id": "DRDO-1019", "full_name": "Mr. Karthik Subramanian", "gender": "Male", "designation": "Scientist E", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Natural Language Processing", "Robotics", "Autonomous Systems"], "projects_associated": ["RoboSoldier", "Project AI-GUARD"], "phone_office": "080-23600019", "email": "karthik.subramanian@cair.drdo.in", "years_of_experience": 10},
    {"employee_id": "DRDO-1020", "full_name": "Dr. Mohan Reddy", "gender": "Male", "designation": "Scientist G", "department": "Electronics & Radar", "lab_acronym": "DLRL", "area_of_expertise": ["Electronic Warfare", "Jamming Systems", "EW Receivers"], "projects_associated": ["Project SAMYUKTA", "EW Suite-2"], "phone_office": "040-27192020", "email": "mohan.reddy@dlrl.drdo.in", "years_of_experience": 23},
    {"employee_id": "DRDO-1021", "full_name": "Dr. Nisha Agarwal", "gender": "Female", "designation": "Scientist F", "department": "Materials Science", "lab_acronym": "DMSRDE", "area_of_expertise": ["Textile Technology", "Ballistic Fabric", "Protective Clothing"], "projects_associated": ["BulletproofVest-3", "NBC Suit"], "phone_office": "0512-2412021", "email": "nisha.agarwal@dmsrde.drdo.in", "years_of_experience": 16},
    {"employee_id": "DRDO-1022", "full_name": "Dr. Harish Chandra", "gender": "Male", "designation": "Scientist E", "department": "Missiles & Strategic Systems", "lab_acronym": "RCI", "area_of_expertise": ["Avionics", "Inertial Navigation", "Gyroscope Systems"], "projects_associated": ["Project AGNI", "NavSystem-4"], "phone_office": "040-24189022", "email": "harish.chandra@rci.drdo.in", "years_of_experience": 13},
    {"employee_id": "DRDO-1023", "full_name": "Ms. Divya Krishnamurthy", "gender": "Female", "designation": "Scientist C", "department": "Aeronautics", "lab_acronym": "ADE", "area_of_expertise": ["Structural Analysis", "FEM Simulation", "Composite Materials"], "projects_associated": ["Project RUSTOM-2"], "phone_office": "080-25051023", "email": "divya.krishnamurthy@ade.drdo.in", "years_of_experience": 3},
    {"employee_id": "DRDO-1024", "full_name": "Dr. Ramesh Bhatt", "gender": "Male", "designation": "Scientist H", "department": "Electronics & Radar", "lab_acronym": "LRDE", "area_of_expertise": ["Active Electronically Scanned Array", "Radar Systems", "Microwave Engineering"], "projects_associated": ["Project ARUDHRA", "Project UTTAM"], "phone_office": "080-25051024", "email": "ramesh.bhatt@lrde.drdo.in", "years_of_experience": 32},
    {"employee_id": "DRDO-1025", "full_name": "Dr. Pooja Saxena", "gender": "Female", "designation": "Scientist E", "department": "Cyber Security", "lab_acronym": "SAG", "area_of_expertise": ["Cryptographic Algorithms", "Secure Communication", "Blockchain"], "projects_associated": ["SecureNet", "QuantumKey-1"], "phone_office": "011-25674025", "email": "pooja.saxena@sag.drdo.in", "years_of_experience": 11},
    {"employee_id": "DRDO-1026", "full_name": "Mr. Ajay Pandey", "gender": "Male", "designation": "Scientist D", "department": "Naval Systems", "lab_acronym": "NSTL", "area_of_expertise": ["Hydrodynamics", "Propulsion Systems", "Marine Engineering"], "projects_associated": ["Project VARUNASTRA"], "phone_office": "0891-2543026", "email": "ajay.pandey@nstl.drdo.in", "years_of_experience": 7},
    {"employee_id": "DRDO-1027", "full_name": "Dr. Smita Kulkarni", "gender": "Female", "designation": "Scientist F", "department": "Life Sciences", "lab_acronym": "DIBER", "area_of_expertise": ["Biomedical Engineering", "Drug Delivery", "Cold Climate Biology"], "projects_associated": ["ColdWarrior", "BioPharma-2"], "phone_office": "01972-252027", "email": "smita.kulkarni@diber.drdo.in", "years_of_experience": 15},
    {"employee_id": "DRDO-1028", "full_name": "Dr. Vinod Tomar", "gender": "Male", "designation": "Scientist G", "department": "Armaments", "lab_acronym": "HEMRL", "area_of_expertise": ["High Energy Materials", "Propellant Chemistry", "Detonation Physics"], "projects_associated": ["Project BRAHMOS", "HEMPropellant-3"], "phone_office": "020-27213028", "email": "vinod.tomar@hemrl.drdo.in", "years_of_experience": 24},
    {"employee_id": "DRDO-1029", "full_name": "Ms. Aarti Singh", "gender": "Female", "designation": "Scientist D", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Data Analytics", "Pattern Recognition", "Neural Networks"], "projects_associated": ["SmartSurveillance", "DataMine-1"], "phone_office": "080-23600029", "email": "aarti.singh@cair.drdo.in", "years_of_experience": 6},
    {"employee_id": "DRDO-1030", "full_name": "Dr. Girish Nair", "gender": "Male", "designation": "Scientist F", "department": "Nuclear Medicine", "lab_acronym": "INMAS", "area_of_expertise": ["Radiobiology", "Nuclear Safety", "Decontamination"], "projects_associated": ["NBC Protection", "RadShield"], "phone_office": "011-23905030", "email": "girish.nair@inmas.drdo.in", "years_of_experience": 19},
    {"employee_id": "DRDO-1031", "full_name": "Dr. Nalini Venkat", "gender": "Female", "designation": "Scientist G", "department": "Electronics & Radar", "lab_acronym": "DLRL", "area_of_expertise": ["Electronic Intelligence", "Signal Intelligence", "EW Systems"], "projects_associated": ["Project SAMYUKTA", "ELINT-3"], "phone_office": "040-27192031", "email": "nalini.venkat@dlrl.drdo.in", "years_of_experience": 22},
    {"employee_id": "DRDO-1032", "full_name": "Mr. Rohit Sharma", "gender": "Male", "designation": "Scientist C", "department": "Materials Science", "lab_acronym": "DMRL", "area_of_expertise": ["Powder Metallurgy", "Titanium Alloys", "3D Printing"], "projects_associated": ["ArmorTech"], "phone_office": "040-24340032", "email": "rohit.sharma@dmrl.drdo.in", "years_of_experience": 4},
    {"employee_id": "DRDO-1033", "full_name": "Dr. Jayashree Murthy", "gender": "Female", "designation": "Scientist F", "department": "Aeronautics", "lab_acronym": "NAL", "area_of_expertise": ["Propulsion Engineering", "Gas Turbines", "Jet Engine Design"], "projects_associated": ["Kaveri Engine", "Project SARAS"], "phone_office": "080-25051033", "email": "jayashree.murthy@nal.drdo.in", "years_of_experience": 18},
    {"employee_id": "DRDO-1034", "full_name": "Dr. Ashok Tripathi", "gender": "Male", "designation": "Scientist H", "department": "Missiles & Strategic Systems", "lab_acronym": "DRDL", "area_of_expertise": ["Hypersonic Technology", "Re-entry Vehicles", "Thermal Protection"], "projects_associated": ["HGV Project", "Project AGNI-6"], "phone_office": "040-24586034", "email": "ashok.tripathi@drdl.drdo.in", "years_of_experience": 29},
    {"employee_id": "DRDO-1035", "full_name": "Ms. Preethi Gopal", "gender": "Female", "designation": "Scientist E", "department": "Naval Systems", "lab_acronym": "NPOL", "area_of_expertise": ["Acoustic Signature", "Stealth Technology", "Vibration Analysis"], "projects_associated": ["NavalSonar-2", "StealthShip-1"], "phone_office": "0484-2575035", "email": "preethi.gopal@npol.drdo.in", "years_of_experience": 12},
    {"employee_id": "DRDO-1036", "full_name": "Dr. Santosh Kumar", "gender": "Male", "designation": "Scientist F", "department": "Life Sciences", "lab_acronym": "DIPAS", "area_of_expertise": ["Cognitive Performance", "Stress Physiology", "Sleep Research"], "projects_associated": ["SoldierPerformance", "AltitudeCare"], "phone_office": "011-23883036", "email": "santosh.kumar@dipas.drdo.in", "years_of_experience": 14},
    {"employee_id": "DRDO-1037", "full_name": "Dr. Vandana Pillai", "gender": "Female", "designation": "Scientist G", "department": "Armaments", "lab_acronym": "ARDE", "area_of_expertise": ["Gun Propulsion", "Artillery Systems", "Barrel Design"], "projects_associated": ["Project DHANUSH", "ATAGS"], "phone_office": "020-27213037", "email": "vandana.pillai@arde.drdo.in", "years_of_experience": 21},
    {"employee_id": "DRDO-1038", "full_name": "Mr. Nitin Kulkarni", "gender": "Male", "designation": "Scientist D", "department": "Cyber Security", "lab_acronym": "SAG", "area_of_expertise": ["Quantum Cryptography", "Post-Quantum Security", "Key Management"], "projects_associated": ["QuantumKey-1", "SecureNet"], "phone_office": "011-25674038", "email": "nitin.kulkarni@sag.drdo.in", "years_of_experience": 8},
    {"employee_id": "DRDO-1039", "full_name": "Dr. Padma Rajan", "gender": "Female", "designation": "Scientist F", "department": "Materials Science", "lab_acronym": "DMSRDE", "area_of_expertise": ["Polymer Chemistry", "Smart Materials", "Camouflage Technology"], "projects_associated": ["CamouflageNet", "NBC Suit"], "phone_office": "0512-2412039", "email": "padma.rajan@dmsrde.drdo.in", "years_of_experience": 16},
    {"employee_id": "DRDO-1040", "full_name": "Dr. Dinesh Choudhary", "gender": "Male", "designation": "Scientist G", "department": "Electronics & Radar", "lab_acronym": "SAC", "area_of_expertise": ["Synthetic Aperture Radar", "Microwave Remote Sensing", "Data Fusion"], "projects_associated": ["Project RISAT", "SAR-Payload-2"], "phone_office": "079-26914040", "email": "dinesh.choudhary@sac.drdo.in", "years_of_experience": 20},
    {"employee_id": "DRDO-1041", "full_name": "Ms. Lavanya Suresh", "gender": "Female", "designation": "Scientist C", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Reinforcement Learning", "Swarm Intelligence", "Multi-Agent Systems"], "projects_associated": ["SwarmDrone", "RoboSoldier"], "phone_office": "080-23600041", "email": "lavanya.suresh@cair.drdo.in", "years_of_experience": 3},
    {"employee_id": "DRDO-1042", "full_name": "Dr. Balasubramanian K", "gender": "Male", "designation": "Scientist H", "department": "Aeronautics", "lab_acronym": "ADE", "area_of_expertise": ["Fly-by-Wire", "Autopilot Systems", "Flight Simulation"], "projects_associated": ["Project AURA", "MALE UAV"], "phone_office": "080-25051042", "email": "bala.k@ade.drdo.in", "years_of_experience": 31},
    {"employee_id": "DRDO-1043", "full_name": "Dr. Shilpa Mathur", "gender": "Female", "designation": "Scientist E", "department": "Nuclear Medicine", "lab_acronym": "INMAS", "area_of_expertise": ["Radiation Therapy", "Nuclear Imaging", "Medical Physics"], "projects_associated": ["RadShield", "MedNuclear-2"], "phone_office": "011-23905043", "email": "shilpa.mathur@inmas.drdo.in", "years_of_experience": 10},
    {"employee_id": "DRDO-1044", "full_name": "Mr. Vikas Yadav", "gender": "Male", "designation": "Scientist D", "department": "Missiles & Strategic Systems", "lab_acronym": "RCI", "area_of_expertise": ["Embedded Software", "Real-Time Systems", "Fault Tolerant Computing"], "projects_associated": ["NavSystem-4", "Project PRITHVI"], "phone_office": "040-24189044", "email": "vikas.yadav@rci.drdo.in", "years_of_experience": 9},
    {"employee_id": "DRDO-1045", "full_name": "Dr. Meghna Das", "gender": "Female", "designation": "Scientist F", "department": "Naval Systems", "lab_acronym": "NSTL", "area_of_expertise": ["Mine Warfare", "Underwater Robotics", "AUV Systems"], "projects_associated": ["Project SHYENA", "AUV-Alpha"], "phone_office": "0891-2543045", "email": "meghna.das@nstl.drdo.in", "years_of_experience": 15},
    {"employee_id": "DRDO-1046", "full_name": "Dr. Rajeev Malhotra", "gender": "Male", "designation": "Scientist G", "department": "Armaments", "lab_acronym": "HEMRL", "area_of_expertise": ["Thermobaric Weapons", "Blast Mechanics", "Shock Wave Physics"], "projects_associated": ["HEMPropellant-3", "BlastSim-1"], "phone_office": "020-27213046", "email": "rajeev.malhotra@hemrl.drdo.in", "years_of_experience": 23},
    {"employee_id": "DRDO-1047", "full_name": "Ms. Tanvi Mishra", "gender": "Female", "designation": "Scientist D", "department": "Electronics & Radar", "lab_acronym": "LRDE", "area_of_expertise": ["Digital Signal Processing", "Waveform Design", "Clutter Suppression"], "projects_associated": ["Project ARUDHRA"], "phone_office": "080-25051047", "email": "tanvi.mishra@lrde.drdo.in", "years_of_experience": 6},
    {"employee_id": "DRDO-1048", "full_name": "Dr. Subramaniam Pillai", "gender": "Male", "designation": "Scientist H", "department": "Life Sciences", "lab_acronym": "DIBER", "area_of_expertise": ["High Altitude Genomics", "Acclimatization", "Molecular Biology"], "projects_associated": ["ColdWarrior", "GeneticAdapt-1"], "phone_office": "01972-252048", "email": "subramaniam.pillai@diber.drdo.in", "years_of_experience": 27},
    {"employee_id": "DRDO-1049", "full_name": "Dr. Anita Jha", "gender": "Female", "designation": "Scientist F", "department": "Materials Science", "lab_acronym": "DMRL", "area_of_expertise": ["Steel Metallurgy", "Heat Treatment", "Failure Analysis"], "projects_associated": ["Project KANCHAN", "ArmorSteel-2"], "phone_office": "040-24340049", "email": "anita.jha@dmrl.drdo.in", "years_of_experience": 17},
    {"employee_id": "DRDO-1050", "full_name": "Mr. Abhishek Chauhan", "gender": "Male", "designation": "Scientist C", "department": "Cyber Security", "lab_acronym": "CAIR", "area_of_expertise": ["Penetration Testing", "Vulnerability Research", "Zero Day Analysis"], "projects_associated": ["Project NETRA"], "phone_office": "080-23600050", "email": "abhishek.chauhan@cair.drdo.in", "years_of_experience": 3},
    {"employee_id": "DRDO-1051", "full_name": "Dr. Geeta Prasad", "gender": "Female", "designation": "Scientist G", "department": "Aeronautics", "lab_acronym": "NAL", "area_of_expertise": ["Avionics Systems", "Navigation Software", "Embedded Avionics"], "projects_associated": ["Project SARAS", "Kaveri Engine"], "phone_office": "080-25051051", "email": "geeta.prasad@nal.drdo.in", "years_of_experience": 20},
    {"employee_id": "DRDO-1052", "full_name": "Dr. Manoj Srivastava", "gender": "Male", "designation": "Scientist F", "department": "Missiles & Strategic Systems", "lab_acronym": "DRDL", "area_of_expertise": ["Seeker Technology", "Infrared Homing", "Target Tracking"], "projects_associated": ["Project NISHANT", "IR Seeker-3"], "phone_office": "040-24586052", "email": "manoj.srivastava@drdl.drdo.in", "years_of_experience": 16},
    {"employee_id": "DRDO-1053", "full_name": "Ms. Haritha Nair", "gender": "Female", "designation": "Scientist E", "department": "Naval Systems", "lab_acronym": "NPOL", "area_of_expertise": ["Hull Form Optimization", "Drag Reduction", "Ship Design"], "projects_associated": ["StealthShip-1", "NavHull-2"], "phone_office": "0484-2575053", "email": "haritha.nair@npol.drdo.in", "years_of_experience": 11},
    {"employee_id": "DRDO-1054", "full_name": "Dr. Prakash Iyer", "gender": "Male", "designation": "Scientist G", "department": "Electronic Warfare", "lab_acronym": "DLRL", "area_of_expertise": ["Radar Warning Receivers", "Countermeasures", "RF Systems"], "projects_associated": ["Project SAMYUKTA", "RWR Suite-4"], "phone_office": "040-27192054", "email": "prakash.iyer@dlrl.drdo.in", "years_of_experience": 24},
    {"employee_id": "DRDO-1055", "full_name": "Dr. Ritu Agarwal", "gender": "Female", "designation": "Scientist F", "department": "Life Sciences", "lab_acronym": "DFRL", "area_of_expertise": ["Microbiology", "Food Safety", "Shelf Life Extension"], "projects_associated": ["FieldRation-5", "SoldierNutrition"], "phone_office": "0821-2362055", "email": "ritu.agarwal@dfrl.drdo.in", "years_of_experience": 14},
    {"employee_id": "DRDO-1056", "full_name": "Mr. Siddharth Verma", "gender": "Male", "designation": "Scientist D", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Object Detection", "Autonomous Navigation", "Sensor Fusion"], "projects_associated": ["SwarmDrone", "Project AI-GUARD"], "phone_office": "080-23600056", "email": "siddharth.verma@cair.drdo.in", "years_of_experience": 7},
    {"employee_id": "DRDO-1057", "full_name": "Dr. Chandrika Rao", "gender": "Female", "designation": "Scientist H", "department": "Armaments", "lab_acronym": "ARDE", "area_of_expertise": ["Rocket Motor Design", "Solid Propellants", "Nozzle Design"], "projects_associated": ["Project PINAKA", "Project BRAHMOS"], "phone_office": "020-27213057", "email": "chandrika.rao@arde.drdo.in", "years_of_experience": 30},
    {"employee_id": "DRDO-1058", "full_name": "Dr. Arun Menon", "gender": "Male", "designation": "Scientist F", "department": "Materials Science", "lab_acronym": "DMSRDE", "area_of_expertise": ["Rubber Technology", "Sealing Systems", "NBC Protective Materials"], "projects_associated": ["NBC Suit", "SealTech-1"], "phone_office": "0512-2412058", "email": "arun.menon@dmsrde.drdo.in", "years_of_experience": 17},
    {"employee_id": "DRDO-1059", "full_name": "Ms. Swathi Krishnan", "gender": "Female", "designation": "Scientist C", "department": "Electronics & Radar", "lab_acronym": "SAC", "area_of_expertise": ["Hyperspectral Imaging", "Ground Penetrating Radar", "Target Classification"], "projects_associated": ["SAR-Payload-2"], "phone_office": "079-26914059", "email": "swathi.krishnan@sac.drdo.in", "years_of_experience": 4},
    {"employee_id": "DRDO-1060", "full_name": "Dr. Ramakrishna Rao", "gender": "Male", "designation": "Scientist H", "department": "Missiles & Strategic Systems", "lab_acronym": "DRDL", "area_of_expertise": ["Scramjet Propulsion", "Air Breathing Engines", "Hypersonic Aerodynamics"], "projects_associated": ["Project BRAHMOS-II", "HypersonicGlide"], "phone_office": "040-24586060", "email": "ramakrishna.rao@drdl.drdo.in", "years_of_experience": 33},
    {"employee_id": "DRDO-1061", "full_name": "Dr. Falguni Shah", "gender": "Female", "designation": "Scientist F", "department": "Nuclear Medicine", "lab_acronym": "INMAS", "area_of_expertise": ["Radiopharmaceuticals", "PET Imaging", "Isotope Production"], "projects_associated": ["MedNuclear-2", "IsotopeR&D"], "phone_office": "011-23905061", "email": "falguni.shah@inmas.drdo.in", "years_of_experience": 15},
    {"employee_id": "DRDO-1062", "full_name": "Mr. Gaurav Rawat", "gender": "Male", "designation": "Scientist D", "department": "Aeronautics", "lab_acronym": "ADE", "area_of_expertise": ["Ground Control Systems", "Data Link", "Mission Planning Software"], "projects_associated": ["MALE UAV", "Project RUSTOM-2"], "phone_office": "080-25051062", "email": "gaurav.rawat@ade.drdo.in", "years_of_experience": 8},
    {"employee_id": "DRDO-1063", "full_name": "Dr. Saranya Krishnamoorthy", "gender": "Female", "designation": "Scientist G", "department": "Cyber Security", "lab_acronym": "SAG", "area_of_expertise": ["Cryptanalysis", "Side Channel Attacks", "Hardware Security"], "projects_associated": ["QuantumKey-1", "HardwareSec-2"], "phone_office": "011-25674063", "email": "saranya.k@sag.drdo.in", "years_of_experience": 22},
    {"employee_id": "DRDO-1064", "full_name": "Dr. Devendra Tiwari", "gender": "Male", "designation": "Scientist F", "department": "Life Sciences", "lab_acronym": "DIPAS", "area_of_expertise": ["Psychological Assessment", "Human Factors", "Ergonomics"], "projects_associated": ["SoldierPerformance", "HumanFactor-3"], "phone_office": "011-23883064", "email": "devendra.tiwari@dipas.drdo.in", "years_of_experience": 13},
    {"employee_id": "DRDO-1065", "full_name": "Ms. Priya Nair", "gender": "Female", "designation": "Scientist E", "department": "Electronic Warfare", "lab_acronym": "DLRL", "area_of_expertise": ["Directed Energy Weapons", "High Power Microwave", "Laser Systems"], "projects_associated": ["DEW Project", "Project KALI"], "phone_office": "040-27192065", "email": "priya.nair@dlrl.drdo.in", "years_of_experience": 10},
    {"employee_id": "DRDO-1066", "full_name": "Dr. Sunil Bajpai", "gender": "Male", "designation": "Scientist G", "department": "Naval Systems", "lab_acronym": "NSTL", "area_of_expertise": ["Heavy Torpedo", "Guidance and Control", "Underwater Propulsion"], "projects_associated": ["Project VARUNASTRA", "HeavyTorp-2"], "phone_office": "0891-2543066", "email": "sunil.bajpai@nstl.drdo.in", "years_of_experience": 24},
    {"employee_id": "DRDO-1067", "full_name": "Dr. Archana Kulkarni", "gender": "Female", "designation": "Scientist F", "department": "Armaments", "lab_acronym": "TBRL", "area_of_expertise": ["Impact Mechanics", "Fragment Analysis", "Penetration Mechanics"], "projects_associated": ["AmmunitionTest-3", "FragSim-1"], "phone_office": "0172-2635067", "email": "archana.kulkarni@tbrl.drdo.in", "years_of_experience": 16},
    {"employee_id": "DRDO-1068", "full_name": "Mr. Vivek Sharma", "gender": "Male", "designation": "Scientist D", "department": "Materials Science", "lab_acronym": "DMRL", "area_of_expertise": ["Nano Materials", "Carbon Nanotubes", "Structural Nano-composites"], "projects_associated": ["NanoArmor-1"], "phone_office": "040-24340068", "email": "vivek.sharma@dmrl.drdo.in", "years_of_experience": 6},
    {"employee_id": "DRDO-1069", "full_name": "Dr. Sudha Venkataraman", "gender": "Female", "designation": "Scientist H", "department": "Electronics & Radar", "lab_acronym": "LRDE", "area_of_expertise": ["Low Observable Technology", "Stealth Radar", "RCS Reduction"], "projects_associated": ["StealthRadar-1", "Project UTTAM"], "phone_office": "080-25051069", "email": "sudha.venkataraman@lrde.drdo.in", "years_of_experience": 29},
    {"employee_id": "DRDO-1070", "full_name": "Dr. Pavan Kumar", "gender": "Male", "designation": "Scientist G", "department": "Artificial Intelligence", "lab_acronym": "CAIR", "area_of_expertise": ["Explainable AI", "Decision Support Systems", "Knowledge Graphs"], "projects_associated": ["Project AI-GUARD", "KnowledgeNet-1"], "phone_office": "080-23600070", "email": "pavan.kumar@cair.drdo.in", "years_of_experience": 21},
    {"employee_id": "DRDO-1071", "full_name": "Ms. Bhavana Reddy", "gender": "Female", "designation": "Scientist C", "department": "Naval Systems", "lab_acronym": "NPOL", "area_of_expertise": ["Marine Corrosion", "Cathodic Protection", "Coatings Technology"], "projects_associated": ["NavHull-2"], "phone_office": "0484-2575071", "email": "bhavana.reddy@npol.drdo.in", "years_of_experience": 2},
    {"employee_id": "DRDO-1072", "full_name": "Dr. Krishnamurthy S", "gender": "Male", "designation": "Scientist H", "department": "Electronic Warfare", "lab_acronym": "DLRL", "area_of_expertise": ["Wideband Jamming", "DRFM Technology", "Threat Simulation"], "projects_associated": ["Project SAMYUKTA", "ThreatSim-2"], "phone_office": "040-27192072", "email": "krishnamurthy.s@dlrl.drdo.in", "years_of_experience": 31},
    {"employee_id": "DRDO-1073", "full_name": "Dr. Nandita Roy", "gender": "Female", "designation": "Scientist F", "department": "Life Sciences", "lab_acronym": "DRDE", "area_of_expertise": ["Chemical Warfare Defence", "Toxicology", "Decontamination Science"], "projects_associated": ["NBC Protection", "ChemDef-3"], "phone_office": "0751-2390073", "email": "nandita.roy@drde.drdo.in", "years_of_experience": 18},
    {"employee_id": "DRDO-1074", "full_name": "Mr. Rahul Gupta", "gender": "Male", "designation": "Scientist D", "department": "Aeronautics", "lab_acronym": "NAL", "area_of_expertise": ["Aircraft Maintenance", "Fatigue Testing", "Non Destructive Testing"], "projects_associated": ["Project HANSA", "NDT Lab"], "phone_office": "080-25051074", "email": "rahul.gupta@nal.drdo.in", "years_of_experience": 8},
    {"employee_id": "DRDO-1075", "full_name": "Dr. Ambika Sharma", "gender": "Female", "designation": "Scientist G", "department": "Missiles & Strategic Systems", "lab_acronym": "RCI", "area_of_expertise": ["Mission Computer", "Software Architecture", "Redundancy Management"], "projects_associated": ["Project AGNI-5", "MissionComp-4"], "phone_office": "040-24189075", "email": "ambika.sharma@rci.drdo.in", "years_of_experience": 25},
    {"employee_id": "DRDO-1076", "full_name": "Dr. Ranjit Biswas", "gender": "Male", "designation": "Scientist F", "department": "Nuclear Medicine", "lab_acronym": "INMAS", "area_of_expertise": ["Radiation Emergency Medicine", "Biodosimetry", "Triage Systems"], "projects_associated": ["NBC Protection", "RadEmergency-1"], "phone_office": "011-23905076", "email": "ranjit.biswas@inmas.drdo.in", "years_of_experience": 17},
    {"employee_id": "DRDO-1077", "full_name": "Ms. Keerthi Pillai", "gender": "Female", "designation": "Scientist E", "department": "Cyber Security", "lab_acronym": "CAIR", "area_of_expertise": ["Mobile Security", "IoT Security", "5G Network Security"], "projects_associated": ["CyberShield", "IoTSec-2"], "phone_office": "080-23600077", "email": "keerthi.pillai@cair.drdo.in", "years_of_experience": 9},
    {"employee_id": "DRDO-1078", "full_name": "Dr. Narayanan M", "gender": "Male", "designation": "Scientist H", "department": "Aeronautics", "lab_acronym": "ADE", "area_of_expertise": ["Stealth Aircraft Design", "Radar Absorbing Materials", "Low RCS Shaping"], "projects_associated": ["Project AURA", "StealthUAV-1"], "phone_office": "080-25051078", "email": "narayanan.m@ade.drdo.in", "years_of_experience": 28},
    {"employee_id": "DRDO-1079", "full_name": "Dr. Savita Rao", "gender": "Female", "designation": "Scientist G", "department": "Materials Science", "lab_acronym": "DMSRDE", "area_of_expertise": ["Fibre Reinforced Plastics", "Thermal Insulation", "Anti-Blast Materials"], "projects_associated": ["ArmorTech", "BlastSim-1"], "phone_office": "0512-2412079", "email": "savita.rao@dmsrde.drdo.in", "years_of_experience": 23},
    {"employee_id": "DRDO-1080", "full_name": "Mr. Tarun Bhatia", "gender": "Male", "designation": "Scientist C", "department": "Electronic Warfare", "lab_acronym": "DLRL", "area_of_expertise": ["Software Defined Radio", "Cognitive EW", "Spectrum Management"], "projects_associated": ["EW Suite-2"], "phone_office": "040-27192080", "email": "tarun.bhatia@dlrl.drdo.in", "years_of_experience": 3}
]

def build_profile_text(person):
    expertise = ', '.join(person['area_of_expertise'])
    projects = ', '.join(person['projects_associated'])
    return (
        f"{person['full_name']} is a {person['designation']} "
        f"in the {person['department']} department at {person['lab_acronym']}. "
        f"Area of expertise includes {expertise}. "
        f"Associated projects are {projects}. "
        f"Has {person['years_of_experience']} years of experience."
    )

def seed():
    existing_count = personnel_collection.count_documents({})
    if existing_count > 0:
        print(f"Database already has {existing_count} records. Skipping seed.")
        return

    print(f"Generating embeddings and inserting {len(personnel_data)} records...")
    for i, person in enumerate(personnel_data):
        profile_text = build_profile_text(person)
        embedding = model.encode(profile_text).tolist()
        person["embedding_vector"] = embedding
        person["profile_text"] = profile_text
        personnel_collection.insert_one(person)
        print(f"  [{i+1}/{len(personnel_data)}] Inserted: {person['full_name']}")

    print("✅ Seed complete! Database populated with 80 DRDO personnel records.")

if __name__ == "__main__":
    seed()